import os
import pandas as pd
import numpy as np
import pickle
from sklearn.metrics.pairwise import cosine_similarity

def clean_and_extract_tags_fallback(text, stopwords):
    # Pure-Python fallback in case spaCy is not installed
    if not isinstance(text, str):
        return ""
    words = text.lower().replace(",", " ").replace(".", " ").split()
    tags = [w for w in words if w.isalpha() and w not in stopwords]
    return ", ".join(tags)

def main():
    print("Starting recommendation model generation...")
    
    # 1. Create models directory if it doesn't exist
    os.makedirs("models", exist_ok=True)
    
    # 2. Check if the raw data file exists
    tsv_filename = "marketing_sample_for_walmart_com-walmart_com_product_review__20200701_20201231__5k_data.tsv"
    if not os.path.exists(tsv_filename):
        print(f"Error: Raw data file '{tsv_filename}' not found.")
        print("Please ensure the raw TSV file is in the root directory.")
        return

    print("Loading raw dataset...")
    train_data = pd.read_csv(tsv_filename, sep='\t')
    
    print("Preprocessing data...")
    # Select columns
    columns_to_keep = [
        'Uniq Id', 'Product Id', 'Product Rating', 'Product Reviews Count', 
        'Product Category', 'Product Brand', 'Product Name', 
        'Product Image Url', 'Product Description', 'Product Tags'
    ]
    train_data = train_data[columns_to_keep]
    
    # Fill missing values without using inplace=True to avoid ChainedAssignmentError
    train_data['Product Rating'] = train_data['Product Rating'].fillna(0)
    train_data['Product Reviews Count'] = train_data['Product Reviews Count'].fillna(0)
    train_data['Product Category'] = train_data['Product Category'].fillna('')
    train_data['Product Brand'] = train_data['Product Brand'].fillna('')
    train_data['Product Description'] = train_data['Product Description'].fillna('')
    
    # Rename columns
    column_name_mapping = {
        'Uniq Id': 'ID',
        'Product Id': 'ProdID',
        'Product Rating': 'Rating',
        'Product Reviews Count': 'ReviewCount',
        'Product Category': 'Category',
        'Product Brand': 'Brand',
        'Product Name': 'Name',
        'Product Image Url': 'ImageURL',
        'Product Description': 'Description',
        'Product Tags': 'Tags'
    }
    train_data = train_data.rename(columns=column_name_mapping)
    
    # Clean ID and ProdID to numeric
    train_data['ID'] = train_data['ID'].str.extract(r'(\d+)').astype(float)
    train_data['ProdID'] = train_data['ProdID'].str.extract(r'(\d+)').astype(float)
    
    # Fill NaNs generated by conversion without using inplace=True
    train_data['ID'] = train_data['ID'].fillna(0)
    train_data['ProdID'] = train_data['ProdID'].fillna(0)
    
    print("Cleaning and extracting tags for text columns...")
    columns_to_extract_tags_from = ['Category', 'Brand', 'Description']
    
    try:
        import spacy
        from spacy.lang.en.stop_words import STOP_WORDS
        print("Using spaCy for tag extraction...")
        nlp = spacy.load("en_core_web_sm")
        
        def clean_and_extract_tags_spacy(text):
            if not isinstance(text, str):
                return ""
            doc = nlp(text.lower())
            tags = [token.text for token in doc if token.is_alpha and token.text not in STOP_WORDS]
            return ', '.join(tags)
            
        for column in columns_to_extract_tags_from:
            train_data[column] = train_data[column].apply(clean_and_extract_tags_spacy)
            
    except Exception as e:
        print("spaCy model loading failed or spaCy not installed. Using fallback text tokenizer...")
        print(f"Details: {e}")
        # Standard English stop words fallback
        STOPWORDS_FALLBACK = {
            'a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', 'arent', 
            'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'cant', 
            'cannot', 'could', 'couldnt', 'did', 'didnt', 'do', 'does', 'doesnt', 'doing', 'dont', 'down', 'during', 
            'each', 'few', 'for', 'from', 'further', 'had', 'hadnt', 'has', 'hasnt', 'have', 'havent', 'having', 'he', 
            'hed', 'hell', 'hes', 'her', 'here', 'heres', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'hows', 
            'i', 'id', 'ill', 'im', 'ive', 'if', 'in', 'into', 'is', 'isnt', 'it', 'its', 'itself', 'lets', 'me', 'more', 
            'most', 'mustnt', 'my', 'myself', 'no', 'nor', 'not', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 
            'ought', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'same', 'shant', 'she', 'shed', 'shell', 'shes', 
            'should', 'shouldnt', 'so', 'some', 'such', 'than', 'that', 'thats', 'the', 'their', 'theirs', 'them', 
            'themselves', 'then', 'there', 'theres', 'these', 'they', 'theyd', 'theyll', 'theyre', 'theyve', 'this', 
            'those', 'through', 'to', 'too', 'under', 'until', 'up', 'very', 'was', 'wasnt', 'we', 'wed', 'well', 
            'were', 'weve', 'werent', 'what', 'whats', 'when', 'whens', 'where', 'wheres', 'which', 'while', 'who', 
            'whos', 'whom', 'why', 'whys', 'with', 'wont', 'would', 'wouldnt', 'you', 'youd', 'youll', 'youre', 
            'youve', 'your', 'yours', 'yourself', 'yourselves'
        }
        for column in columns_to_extract_tags_from:
            train_data[column] = train_data[column].apply(lambda x: clean_and_extract_tags_fallback(x, STOPWORDS_FALLBACK))

    # Combine tags for final Tags column
    print("Combining tags...")
    train_data.reset_index(drop=True, inplace=True)
    train_data['Tags'] = train_data[columns_to_extract_tags_from].apply(lambda row: ', '.join(filter(None, row)), axis=1)
    
    # Save clean dataset
    print("Saving models/clean_data.csv...")
    train_data.to_csv("models/clean_data.csv", index=False)
    
    # 3. Collaborative Filtering Recommendations
    print("Generating Collaborative Filtering Recommendations...")
    target_user_id = train_data['ID'].iloc[4] # target user id
    
    # Pivot matrix
    user_item_matrix = train_data.pivot_table(index='ID', columns='ProdID', values='Rating', aggfunc='mean').fillna(0).astype(int)
    
    # User similarities
    user_similarity = cosine_similarity(user_item_matrix)
    target_user_index = user_item_matrix.index.get_loc(target_user_id)
    user_similarities = user_similarity[target_user_index]
    
    # Sort similar users
    similar_user_indices = user_similarities.argsort()[::-1][1:]
    
    recommend_items = []
    top_n = 10
    for user_index in similar_user_indices:
        rated_by_similar_user = user_item_matrix.iloc[user_index]
        not_rated_by_target_user = (rated_by_similar_user == 0) & (user_item_matrix.iloc[target_user_index] == 0)
        recommend_items.extend(user_item_matrix.columns[not_rated_by_target_user][:top_n])
        
    recommended_items_details = train_data[train_data['ProdID'].isin(recommend_items)][['Name', 'ReviewCount', 'Brand', 'ImageURL', 'Rating']].copy()
    
    # Save collaborative filtering recommendation CSV
    print("Saving models/collaborative_filtering_recommendation.csv...")
    recommended_items_details.to_csv("models/collaborative_filtering_recommendation.csv", index=False)
    
    # Save pickled collaborative filtering model object
    print("Saving models/collaborative_recommendations.pkl...")
    with open("models/collaborative_recommendations.pkl", "wb") as f:
        pickle.dump(recommended_items_details, f)
        
    print("All recommendation models generated successfully!")

if __name__ == "__main__":
    main()
